//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> f1 { get; set; }
        public Nullable<decimal> f2 { get; set; }
        public Nullable<decimal> f3 { get; set; }
        public Nullable<decimal> f4 { get; set; }
        public Nullable<decimal> f5 { get; set; }
        public Nullable<decimal> f6 { get; set; }
        public Nullable<decimal> f7 { get; set; }
        public Nullable<decimal> f8 { get; set; }
        public Nullable<decimal> f9 { get; set; }
        public Nullable<decimal> f10 { get; set; }
        public Nullable<decimal> f11 { get; set; }
        public Nullable<decimal> f12 { get; set; }
        public Nullable<decimal> f13 { get; set; }
        public Nullable<decimal> f14 { get; set; }
        public Nullable<decimal> f15 { get; set; }
    
        public virtual User User { get; set; }
    }
}
